trigger:
  branches:
    include:
    - master
    - releases/*
    exclude:
    - refs/tag/*

pool:
  vmImage: 'macOS-10.13'

steps:
- checkout: self
  path: react-native-azurenotificationhub

- script: |
    git clone https://github.com/phongcao/react-native-azurenotificationhub-sample.git ../react-native-azurenotificationhub-sample
  displayName: 'Cloning react-native-azurenotificationhub-sample'

- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node'

- script: npm install
  displayName: 'Install dependencies'
  workingDirectory: '../react-native-azurenotificationhub-sample'

- script: |
    rm -R ../react-native-azurenotificationhub-sample/node_modules/react-native-azurenotificationhub
    cp -R ../react-native-azurenotificationhub ../react-native-azurenotificationhub-sample/node_modules
  displayName: 'Copying react-native-azurenotificationhub'  

- script: npm run lint
  displayName: 'Run lint'
  workingDirectory: '../react-native-azurenotificationhub-sample'

- script: npm run test
  displayName: 'Run unit tests'
  workingDirectory: '../react-native-azurenotificationhub-sample'

- task: Gradle@2
  displayName: 'Building Android'
  inputs:
    workingDirectory: '../react-native-azurenotificationhub-sample/android'
    gradleWrapperFile: '../react-native-azurenotificationhub-sample/android/gradlew'
    tasks: 'assembleRelease'
  continueOnError: false

- script: |
    pod install
    sudo cp -R ../node_modules/react-native-azurenotificationhub/ios Pods/RNAzureNotificationHub
  displayName: 'Install CocoaPods dependencies'
  workingDirectory: '../react-native-azurenotificationhub-sample/ios'

- task: Xcode@5
  displayName: 'Building iOS'
  inputs:
    actions: 'build'
    scheme: 'ReactNativeAzureNotificationHubSample'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '../react-native-azurenotificationhub-sample/ios/ReactNativeAzureNotificationHubSample.xcworkspace'
    xcodeVersion: '10'
    signingOption: 'nosign'
    useXcpretty: 'false'